/*
 * Shared vocabulary: 20 categories, 40 terms each, every term carrying the
 * words most likely to be said while describing it. Written at a sixth-grade
 * reading level throughout — a term nobody at the table can read is a dead
 * card, not a hard one.
 *
 * Storage format is one string per term:
 *
 *     'Elephant|trunk,gray,tusk,africa,huge'
 *      ^ the term  ^ the related words, lower case
 *
 * A string rather than an object per term, because this file ships to phones
 * and 800 objects of two keys each is most of a hundred kilobytes of
 * punctuation. Parsed once at load into { word, related, category }.
 *
 * The related words are the point of the file. Forbidden Words bans them,
 * Star Words hints with them, What Am I leaves them alone — but they are
 * written for the banning case, which is the demanding one: five words a
 * describer would reach for first, not five facts about the thing.
 *
 * See _README.md in any of the three games for how each uses them.
 */
window.Vocab = (function () {
  const DATA = {
    'Animals': [
      'Elephant|trunk,gray,tusk,africa,huge',
      'Penguin|antarctica,waddle,swim,black,bird',
      'Giraffe|neck,tall,spots,africa,leaves',
      'Dolphin|ocean,smart,swim,fish,jump',
      'Rabbit|hop,ears,carrot,bunny,fluffy',
      'Squirrel|nut,tree,tail,acorn,climb',
      'Butterfly|wings,caterpillar,flower,fly,colorful',
      'Alligator|teeth,swamp,reptile,crocodile,jaw',
      'Kangaroo|australia,hop,pouch,jump,joey',
      'Owl|night,hoot,bird,wise,eyes',
      'Tiger|stripes,cat,orange,jungle,roar',
      'Camel|hump,desert,sand,ride,water',
      'Frog|jump,pond,green,tadpole,croak',
      'Eagle|bird,fly,bald,talons,soar',
      'Horse|ride,gallop,saddle,hoof,mane',
      'Bat|night,cave,fly,wings,vampire',
      'Wolf|howl,pack,dog,forest,moon',
      'Turtle|shell,slow,pond,reptile,swim',
      'Bee|honey,sting,buzz,flower,hive',
      'Whale|ocean,huge,blue,spout,mammal',
      'Monkey|banana,tree,swing,ape,tail',
      'Zebra|stripes,horse,africa,black,white',
      'Spider|web,eight,legs,creepy,bug',
      'Shark|teeth,ocean,fin,bite,fish',
      'Bear|honey,woods,grizzly,cave,claws',
      'Snake|slither,hiss,venom,reptile,scales',
      'Deer|antlers,forest,fawn,run,woods',
      'Ant|tiny,colony,hill,bug,queen',
      'Chicken|egg,farm,cluck,rooster,feather',
      'Goat|beard,milk,farm,horns,butt',
      'Fox|red,sly,tail,forest,clever',
      'Crab|claw,beach,sideways,shell,ocean',
      'Peacock|feathers,tail,blue,bird,show',
      'Hippo|water,huge,africa,mouth,river',
      'Moose|antlers,canada,big,deer,forest',
      'Octopus|eight,arms,ocean,ink,suckers',
      'Lizard|reptile,tail,scales,desert,crawl',
      'Beaver|dam,teeth,wood,river,tail',
      'Parrot|talk,colorful,bird,pirate,feathers',
      'Raccoon|mask,trash,night,stripes,paws',
      'Panda|bamboo,black,white,china,bear',
      'Flamingo|pink,leg,stand,wade,bird',
      'Koala|eucalyptus,australia,tree,sleep,gray',
      'Otter|river,float,playful,fur,swim',
      'Porcupine|quills,sharp,spines,slow,rodent',
      'Hedgehog|spines,curl,small,ball,snuffle',
      'Walrus|tusks,blubber,arctic,whiskers,flop',
      'Chameleon|color,change,tongue,lizard,eyes',
      'Meerkat|stand,desert,lookout,burrow,group',
      'Sloth|slow,hang,tree,claws,upside down'
    ],

    'Food and Drink': [
      'Pizza|cheese,slice,pepperoni,italian,crust',
      'Pancake|syrup,breakfast,flat,flip,batter',
      'Popcorn|movie,kernel,butter,pop,corn',
      'Spaghetti|noodles,sauce,italian,pasta,meatball',
      'Watermelon|seeds,red,summer,fruit,slice',
      'Sandwich|bread,lunch,slice,meat,layers',
      'Ice cream|cold,cone,scoop,dessert,sweet',
      'Taco|shell,mexican,meat,fold,salsa',
      'Broccoli|green,vegetable,tree,healthy,stalk',
      'Cereal|milk,bowl,breakfast,box,crunch',
      'Pickle|cucumber,sour,jar,green,brine',
      'Bacon|pig,crispy,breakfast,strip,fry',
      'Pretzel|salt,twist,snack,knot,bread',
      'Lemonade|sour,sweet,stand,summer,drink',
      'Burrito|wrap,mexican,beans,rice,tortilla',
      'Pineapple|spiky,tropical,yellow,fruit,rings',
      'Waffle|squares,syrup,breakfast,iron,batter',
      'Mustard|yellow,hotdog,condiment,squeeze,tangy',
      'Marshmallow|campfire,white,soft,roast,smore',
      'Sushi|rice,fish,japan,roll,seaweed',
      'Pumpkin|orange,halloween,pie,carve,gourd',
      'Cupcake|frosting,small,birthday,cake,wrapper',
      'Noodle|long,soup,pasta,slurp,ramen',
      'Honey|bee,sticky,sweet,jar,golden',
      'Salsa|chips,tomato,spicy,dip,mexican',
      'Toast|bread,butter,burnt,pop,breakfast',
      'Milkshake|straw,thick,cold,blend,ice cream',
      'Cinnamon|spice,roll,brown,sweet,stick',
      'Meatball|round,spaghetti,beef,sauce,ground',
      'Cabbage|leaves,green,slaw,vegetable,round',
      'Doughnut|hole,glaze,round,fried,sprinkles',
      'Peanut|shell,butter,nut,allergy,salty',
      'Soup|bowl,spoon,hot,broth,slurp',
      'Grapes|bunch,purple,vine,fruit,raisin',
      'Omelet|eggs,fold,breakfast,cheese,pan',
      'Corn|cob,kernel,yellow,butter,field',
      'Chili|spicy,beans,bowl,pepper,stew',
      'Yogurt|cup,creamy,spoon,fruit,milk',
      'Biscuit|flaky,gravy,bread,oven,south',
      'Smoothie|blend,fruit,straw,cold,drink',
      'Bagel|hole,chewy,cream cheese,round,toast',
      'Applesauce|jar,mushy,sweet,apples,spoon',
      'Granola|oats,crunchy,bar,cluster,honey',
      'Guacamole|avocado,green,dip,chips,mash',
      'Coleslaw|cabbage,shredded,creamy,side,picnic',
      'Pita|pocket,flat,bread,stuff,round',
      'Oatmeal|hot,bowl,breakfast,mushy,oats',
      'Jerky|dried,meat,chewy,strip,salty',
      'Sherbet|frozen,fruit,scoop,icy,orange',
      'Casserole|dish,bake,layers,oven,mixed'
    ],

    'Sports and Games': [
      'Basketball|hoop,dribble,court,dunk,net',
      'Soccer|goal,kick,field,ball,world cup',
      'Skateboard|wheels,ramp,trick,ride,board',
      'Swimming|pool,stroke,lap,water,dive',
      'Bowling|pins,strike,lane,ball,alley',
      'Tennis|racket,net,serve,court,love',
      'Chess|board,king,queen,checkmate,pieces',
      'Baseball|bat,pitch,home run,diamond,glove',
      'Hockey|puck,ice,stick,goalie,rink',
      'Gymnastics|flip,beam,tumble,mat,vault',
      'Volleyball|net,spike,serve,beach,team',
      'Karate|belt,kick,dojo,chop,martial',
      'Surfing|wave,board,ocean,ride,beach',
      'Marathon|run,miles,race,finish,long',
      'Archery|bow,arrow,target,aim,bullseye',
      'Wrestling|mat,pin,grapple,takedown,singlet',
      'Golf|club,hole,green,tee,putt',
      'Fishing|rod,bait,hook,lake,catch',
      'Cycling|bike,pedal,helmet,race,wheels',
      'Boxing|gloves,ring,punch,round,knockout',
      'Football|touchdown,helmet,tackle,field,quarterback',
      'Ping-pong|paddle,table,tennis,net,bounce',
      'Skiing|snow,slope,poles,mountain,lift',
      'Ice skating|rink,blades,glide,frozen,spin',
      'Jump rope|skip,turn,rope,double,jump',
      'Hopscotch|chalk,squares,hop,sidewalk,stone',
      'Tag|chase,it,run,playground,touch',
      'Hide and seek|count,hide,find,seek,base',
      'Checkers|board,king,jump,red,black',
      'Dodgeball|throw,dodge,gym,ball,out',
      'Kickball|kick,base,run,playground,ball',
      'Track|run,lap,relay,sprint,field',
      'Diving|board,pool,splash,flip,water',
      'Sledding|snow,hill,slide,winter,ride',
      'Rowing|oar,boat,crew,water,stroke',
      'Climbing|wall,rope,harness,rock,grip',
      'Trampoline|bounce,jump,springs,mat,flip',
      'Frisbee|throw,disc,catch,park,fly',
      'Puzzle|pieces,fit,jigsaw,picture,solve',
      'Scoreboard|points,game,numbers,lights,total',
      'Rugby|scrum,oval,tackle,try,field',
      'Badminton|shuttlecock,racket,net,light,court',
      'Lacrosse|stick,net,catch,field,cradle',
      'Fencing|sword,mask,lunge,foil,point',
      'Curling|stone,ice,sweep,broom,slide',
      'Snowboarding|board,snow,slope,strap,ride',
      'Paintball|splat,mask,shoot,team,field',
      'Horseshoes|toss,stake,ringer,pit,clang',
      'Tug of war|rope,pull,teams,line,strain',
      'Relay race|baton,pass,team,legs,hand off'
    ],

    'School': [
      'Backpack|straps,books,carry,shoulder,zipper',
      'Homework|assignment,due,night,school,practice',
      'Chalkboard|chalk,erase,green,write,teacher',
      'Recess|playground,break,outside,play,lunch',
      'Library|books,quiet,shelves,check out,read',
      'Principal|office,boss,school,in charge,rules',
      'Cafeteria|lunch,tray,tables,food,line',
      'Locker|combination,hallway,metal,door,stuff',
      'Field trip|bus,museum,permission,class,trip',
      'Quiz|test,short,grade,questions,pop',
      'Ruler|inches,measure,straight,twelve,line',
      'Notebook|paper,spiral,write,pages,lined',
      'Eraser|pink,rub,pencil,mistake,rubber',
      'Alphabet|letters,abc,twenty-six,order,sing',
      'Fractions|math,half,numerator,parts,pizza',
      'Bell|ring,class,period,sound,end',
      'Report card|grades,letters,home,quarter,sign',
      'Detention|trouble,stay,after,punishment,office',
      'Science fair|project,board,experiment,judge,volcano',
      'Globe|earth,spin,map,round,countries',
      'Microscope|slide,lens,tiny,look,science',
      'Calculator|numbers,buttons,math,add,screen',
      'Yearbook|photos,sign,memories,class,year',
      'Assembly|gym,gather,speaker,students,announcement',
      'Substitute|teacher,fill in,absent,temporary,class',
      'Spelling bee|words,spell,stage,microphone,contest',
      'Crossing guard|street,stop,vest,walk,safety',
      'Attendance|roll,here,absent,list,call',
      'Marker|cap,color,draw,smell,write',
      'Stapler|staple,papers,click,office,attach',
      'Playground|swings,slide,recess,outside,kids',
      'Textbook|heavy,chapter,pages,subject,read',
      'Essay|write,paragraphs,topic,pages,draft',
      'Bus driver|wheel,route,stop,students,yellow',
      'Gym class|change,run,whistle,sneakers,exercise',
      'Diploma|graduate,paper,scroll,ceremony,finish',
      'Hall pass|bathroom,permission,leave,slip,hallway',
      'Desk|chair,sit,drawer,write,front',
      'Group project|team,share,partner,divide,present',
      'Summer break|vacation,june,out,months,free',
      'Cursive|loops,handwriting,connect,practice,script',
      'Pencil sharpener|crank,point,shavings,wall,twist',
      'Protractor|angle,degrees,half circle,measure,math',
      'Vocabulary|words,list,meaning,learn,quiz',
      'Recitation|say,memorize,aloud,front,repeat',
      'Locker room|change,gym,benches,lockers,smell',
      'Study hall|quiet,period,homework,room,work',
      'Honor roll|grades,list,posted,high,names',
      'Field day|races,outside,ribbons,games,spring',
      'Chalk dust|white,erase,board,cloud,fine'
    ],

    'Weather and Seasons': [
      'Thunderstorm|lightning,rain,loud,clouds,boom',
      'Snowflake|winter,white,unique,fall,crystal',
      'Rainbow|colors,rain,arch,sun,seven',
      'Hurricane|wind,storm,eye,ocean,evacuate',
      'Tornado|funnel,spin,wind,twister,damage',
      'Fog|thick,cloud,ground,see,morning',
      'Drought|dry,no rain,crops,water,long',
      'Blizzard|snow,wind,whiteout,storm,cold',
      'Sunrise|morning,east,orange,dawn,up',
      'Sunset|evening,west,orange,dusk,down',
      'Hail|ice,balls,storm,fall,dent',
      'Autumn|leaves,fall,orange,october,harvest',
      'Spring|flowers,bloom,rain,green,april',
      'Summer|hot,vacation,beach,july,sun',
      'Winter|cold,snow,coat,december,ice',
      'Humidity|sticky,damp,air,muggy,wet',
      'Frost|ice,window,morning,cold,thin',
      'Monsoon|rain,season,flood,wind,asia',
      'Heat wave|hot,days,record,fan,long',
      'Puddle|water,rain,splash,jump,shallow',
      'Icicle|hang,ice,roof,pointy,drip',
      'Breeze|gentle,wind,cool,light,blow',
      'Flood|water,rise,river,damage,rescue',
      'Lightning|bolt,flash,strike,storm,electric',
      'Cloud|sky,white,fluffy,rain,float',
      'Windmill|blades,wind,spin,farm,power',
      'Umbrella|rain,open,handle,cover,wet',
      'Forecast|predict,weather,tomorrow,report,chance',
      'Barometer|pressure,measure,weather,instrument,air',
      'Avalanche|snow,mountain,slide,rush,bury',
      'Dew|morning,grass,drops,wet,dawn',
      'Sleet|ice,rain,mix,falling,slippery',
      'Thermometer|degrees,measure,temperature,mercury,read',
      'Shade|shadow,cool,tree,out of,sun',
      'Overcast|gray,cloudy,dull,sky,covered',
      'Groundhog|shadow,february,spring,burrow,predict',
      'Solstice|longest,shortest,day,sun,june',
      'Equinox|equal,day,night,spring,fall',
      'Chill|cold,shiver,air,slight,brisk',
      'Downpour|heavy,rain,sudden,soaked,pour',
      'Wind chill|colder,feels,factor,bite,air',
      'Rain gauge|measure,inches,tube,collect,yard',
      'Weather vane|arrow,roof,wind,point,spin',
      'Sandstorm|desert,blowing,grit,dark,wind',
      'Slush|melting,gray,wet,snow,mush',
      'Thaw|melt,warm,spring,soften,ice',
      'Squall|sudden,gust,brief,storm,line',
      'Whiteout|blind,snow,nothing,storm,white',
      'Cold front|drop,line,change,weather,push',
      'Mudslide|rain,hill,slide,earth,rush'
    ],

    'Body and Health': [
      'Elbow|arm,bend,joint,funny bone,point',
      'Sneeze|achoo,nose,tissue,cold,blow',
      'Heartbeat|pulse,thump,chest,rhythm,blood',
      'Bandage|cut,cover,sticky,wound,heal',
      'Vitamin|pill,healthy,c,daily,nutrient',
      'Fingernail|clip,hand,grow,file,tip',
      'Eyebrow|hair,eye,above,raise,face',
      'Muscle|strong,flex,arm,lift,bicep',
      'Skeleton|bones,skull,body,inside,halloween',
      'Braces|teeth,straight,metal,dentist,wires',
      'Fever|hot,sick,temperature,thermometer,degrees',
      'Yawn|tired,mouth,sleepy,open,contagious',
      'Blister|rub,skin,shoe,bubble,sore',
      'Stethoscope|doctor,listen,heart,chest,neck',
      'Sunburn|red,peel,beach,skin,sun',
      'Hiccup|breath,sound,water,scare,stop',
      'Crutches|leg,broken,walk,armpit,help',
      'Allergy|sneeze,pollen,react,shot,peanut',
      'Cavity|tooth,dentist,drill,filling,sugar',
      'Shiver|cold,shake,teeth,body,chatter',
      'Bruise|purple,bump,skin,hurt,mark',
      'Sleep|bed,night,dream,eight hours,rest',
      'Exercise|workout,sweat,gym,healthy,move',
      'Lungs|breathe,air,chest,two,oxygen',
      'Stomach|belly,food,digest,growl,middle',
      'Thumb|finger,hand,up,opposable,short',
      'Knee|leg,bend,cap,scrape,joint',
      'Freckle|spot,face,brown,sun,small',
      'Sprain|ankle,twist,swell,ice,injury',
      'Dentist|teeth,drill,clean,chair,floss',
      'Wheelchair|wheels,push,sit,ramp,roll',
      'Hearing aid|ear,sound,volume,small,help',
      'Glasses|see,lenses,frames,nose,blurry',
      'Sunscreen|spray,lotion,burn,beach,spf',
      'Cast|broken,arm,sign,plaster,heal',
      'Toothbrush|paste,teeth,brush,bristles,morning',
      'Nurse|hospital,care,scrubs,doctor,patient',
      'Ambulance|siren,hospital,emergency,truck,lights',
      'Pulse|wrist,beat,count,heart,check',
      'Stretch|reach,muscle,before,limber,arms',
      'Ankle|foot,leg,joint,twist,between',
      'Wrist|hand,arm,bend,watch,joint',
      'Eyelash|lashes,eye,curl,blink,tiny',
      'Tonsils|throat,remove,swollen,back,pair',
      'Immune system|fight,germs,defend,body,protect',
      'Checkup|doctor,yearly,exam,visit,routine',
      'Splint|hold,straight,finger,brace,support',
      'Perspire|sweat,hot,damp,skin,exercise',
      'Nutrient|food,body,vitamin,fuel,healthy',
      'Posture|stand,straight,slouch,back,sit'
    ],

    'Jobs': [
      'Firefighter|hose,truck,rescue,flames,helmet',
      'Astronaut|space,rocket,suit,moon,nasa',
      'Chef|cook,kitchen,hat,restaurant,recipe',
      'Veterinarian|animals,doctor,pets,clinic,shots',
      'Plumber|pipes,leak,wrench,sink,water',
      'Photographer|camera,pictures,shoot,lens,click',
      'Lifeguard|pool,whistle,rescue,chair,swim',
      'Farmer|crops,tractor,barn,field,harvest',
      'Pilot|plane,fly,cockpit,airport,captain',
      'Electrician|wires,power,outlet,fix,voltage',
      'Librarian|books,quiet,shelves,check out,catalog',
      'Mechanic|car,engine,fix,garage,tools',
      'Journalist|news,write,story,report,paper',
      'Architect|design,building,blueprint,plans,draw',
      'Coach|team,whistle,practice,players,sideline',
      'Dentist|teeth,drill,chair,clean,cavity',
      'Judge|court,gavel,robe,law,decide',
      'Carpenter|wood,hammer,build,nails,saw',
      'Scientist|lab,experiment,coat,research,test',
      'Barber|hair,cut,clippers,chair,shave',
      'Zookeeper|animals,feed,cages,zoo,care',
      'Translator|language,words,speak,convert,two',
      'Park ranger|forest,trail,hat,park,protect',
      'Mail carrier|letters,mail,route,truck,deliver',
      'Baker|bread,oven,dough,pastry,flour',
      'Engineer|design,build,math,solve,machine',
      'Detective|clues,case,solve,mystery,investigate',
      'Tailor|sew,clothes,measure,fit,needle',
      'Pharmacist|medicine,pills,counter,prescription,drug',
      'Referee|whistle,call,foul,stripes,game',
      'Custodian|clean,mop,school,keys,building',
      'Paramedic|ambulance,emergency,rescue,medical,siren',
      'Welder|metal,torch,sparks,mask,join',
      'Cartoonist|draw,comics,funny,panels,strip',
      'Surveyor|land,measure,tripod,boundary,map',
      'Tour guide|group,history,show,visitors,talk',
      'Beekeeper|hives,honey,suit,smoke,bees',
      'Programmer|code,computer,software,type,bug',
      'Marine biologist|ocean,study,fish,research,dive',
      'Meteorologist|weather,forecast,map,storm,predict',
      'Optometrist|eyes,glasses,chart,exam,vision',
      'Sign painter|letters,brush,shop,hand,paint',
      'Locksmith|keys,locks,pick,cut,open',
      'Florist|flowers,arrange,shop,bouquet,vase',
      'Butcher|meat,cut,counter,apron,shop',
      'Roofer|shingles,ladder,top,nail,house',
      'Air traffic controller|tower,planes,radar,direct,radio',
      'Costume designer|sew,stage,fit,fabric,character',
      'Blacksmith|forge,anvil,hammer,iron,heat',
      'Sound engineer|mix,levels,board,audio,record'
    ],

    'Around the House': [
      'Doorbell|ring,press,visitor,front,chime',
      'Staircase|steps,up,railing,climb,floor',
      'Vacuum|carpet,suck,clean,cord,dust',
      'Refrigerator|cold,food,door,kitchen,magnets',
      'Closet|clothes,hangers,door,storage,inside',
      'Mailbox|letters,flag,curb,mail,open',
      'Fireplace|logs,chimney,warm,mantel,burn',
      'Chandelier|hang,lights,ceiling,fancy,crystal',
      'Blanket|bed,warm,cover,fold,soft',
      'Dishwasher|plates,soap,kitchen,load,clean',
      'Toaster|bread,pop,slots,brown,plug',
      'Attic|top,storage,dusty,ladder,boxes',
      'Basement|down,stairs,cellar,under,dark',
      'Porch|front,steps,swing,outside,sit',
      'Curtain|window,pull,fabric,rod,cover',
      'Faucet|water,sink,turn,drip,handle',
      'Broom|sweep,bristles,floor,handle,dust',
      'Alarm clock|wake,ring,morning,snooze,bedside',
      'Bookshelf|books,shelves,wall,stack,wood',
      'Laundry|wash,clothes,basket,dryer,fold',
      'Thermostat|temperature,wall,heat,dial,set',
      'Rug|floor,carpet,lay,soft,area',
      'Garage|car,door,park,tools,open',
      'Sofa|sit,couch,cushions,living room,lounge',
      'Mirror|reflect,glass,look,wall,face',
      'Pillow|head,sleep,soft,case,bed',
      'Microwave|heat,beep,minute,popcorn,kitchen',
      'Sprinkler|water,lawn,spray,grass,hose',
      'Hallway|corridor,narrow,doors,walk,between',
      'Windowsill|ledge,plant,window,sit,under',
      'Screen door|mesh,bugs,slam,porch,open',
      'Ceiling fan|blades,spin,cool,above,pull',
      'Junk drawer|mess,batteries,tape,stuff,kitchen',
      'Smoke alarm|beep,ceiling,battery,fire,chirp',
      'Doormat|welcome,wipe,feet,front,rug',
      'Freezer|ice,cold,frozen,drawer,below',
      'Nightlight|dark,plug,glow,hallway,small',
      'Bathtub|water,soak,drain,soap,bathroom',
      'Fence|yard,posts,gate,wood,around',
      'Recycling bin|blue,cans,paper,curb,sort',
      'Utility room|washer,sink,back,laundry,storage',
      'Baseboard|trim,wall,bottom,strip,floor',
      'Light switch|flip,wall,on,off,plate',
      'Extension cord|long,plug,reach,outlet,coil',
      'Coat rack|hooks,hang,entry,stand,jackets',
      'Step stool|reach,fold,short,climb,small',
      'Circuit breaker|panel,trip,flip,power,box',
      'Water heater|tank,hot,basement,pilot,cylinder',
      'Gutter|roof,rain,leaves,clog,channel',
      'Weather stripping|seal,door,draft,strip,gap'
    ],

    'Clothes': [
      'Raincoat|wet,hood,waterproof,yellow,rain',
      'Sneakers|laces,run,shoes,rubber,gym',
      'Mittens|hands,winter,thumb,pair,warm',
      'Scarf|neck,wrap,winter,long,knit',
      'Overalls|straps,denim,farm,bib,pants',
      'Sandals|open,toes,summer,straps,feet',
      'Sweater|knit,warm,pullover,wool,sleeves',
      'Baseball cap|brim,head,hat,adjust,team',
      'Backpack|straps,shoulders,carry,school,zipper',
      'Necktie|knot,collar,suit,neck,dress',
      'Pajamas|sleep,bed,night,soft,set',
      'Uniform|same,school,work,dress code,required',
      'Boots|tall,feet,mud,laces,leather',
      'Costume|dress up,halloween,pretend,outfit,play',
      'Belt|waist,buckle,loops,hold,pants',
      'Hoodie|hood,sweatshirt,pocket,pull,casual',
      'Sunglasses|eyes,dark,sun,lenses,shade',
      'Apron|cook,tie,front,kitchen,protect',
      'Swimsuit|pool,water,beach,wet,suit',
      'Gloves|fingers,hands,winter,pair,warm',
      'Zipper|teeth,pull,close,jacket,stuck',
      'Button|hole,shirt,sew,round,fasten',
      'Pocket|hold,pants,reach,inside,keep',
      'Slippers|soft,feet,house,warm,shuffle',
      'Helmet|head,protect,bike,hard,strap',
      'Jersey|number,team,sport,shirt,name',
      'Skirt|hem,wear,legs,twirl,dress',
      'Vest|sleeveless,over,shirt,layer,zip',
      'Socks|feet,pair,shoes,toes,drawer',
      'Shoelace|tie,knot,shoe,loop,string',
      'Turtleneck|neck,high,collar,sweater,pull',
      'Poncho|rain,over,head,cover,cape',
      'Earmuffs|ears,cold,band,winter,fuzzy',
      'Bandana|square,head,tie,cloth,neck',
      'Flip-flops|beach,toes,slap,rubber,summer',
      'Suspenders|shoulders,hold,pants,straps,clip',
      'Wristwatch|time,wrist,strap,face,tick',
      'Cardigan|open,buttons,sweater,layer,front',
      'Snow pants|winter,waterproof,sled,bulky,legs',
      'Cleats|spikes,grip,field,shoes,soccer',
      'Blazer|jacket,buttons,dressy,lapel,fitted',
      'Leggings|stretchy,tight,legs,thin,pull on',
      'Trench coat|long,belt,rain,tan,collar',
      'Bowtie|neck,knot,formal,small,clip',
      'Windbreaker|light,jacket,zip,wind,thin',
      'Beanie|knit,head,winter,pull,cap',
      'Loafers|slip on,no laces,shoes,leather,flat',
      'Denim|jeans,blue,tough,fabric,pants',
      'Hem|edge,bottom,sew,fold,pants',
      'Collar|neck,shirt,fold,button,top'
    ],

    'Transportation': [
      'Submarine|underwater,periscope,navy,dive,sub',
      'Helicopter|blades,hover,rotor,fly,chopper',
      'Bicycle|pedal,two wheels,handlebars,ride,chain',
      'Ferry|boat,cars,water,cross,dock',
      'Ambulance|siren,hospital,emergency,lights,rush',
      'Subway|underground,train,city,tunnel,station',
      'Hot air balloon|basket,float,burner,sky,rise',
      'Motorcycle|two wheels,helmet,engine,ride,fast',
      'Tractor|farm,field,plow,slow,wheels',
      'Canoe|paddle,water,narrow,river,tip',
      'Skateboard|deck,wheels,trick,ride,ramp',
      'School bus|yellow,stop sign,students,driver,route',
      'Sailboat|wind,sail,mast,water,rope',
      'Rocket|launch,space,fuel,countdown,blast',
      'Elevator|floors,buttons,up,doors,building',
      'Escalator|stairs,moving,mall,step,ride',
      'Taxi|cab,fare,yellow,hail,driver',
      'Snowmobile|snow,track,winter,ride,engine',
      'Wagon|pull,handle,red,wheels,cart',
      'Cruise ship|ocean,vacation,huge,deck,cabins',
      'Gondola|venice,pole,canal,boat,narrow',
      'Fire truck|red,ladder,siren,hose,firefighter',
      'Scooter|kick,handlebars,two wheels,ride,fold',
      'Cable car|hill,wire,san francisco,ride,track',
      'Jet|plane,fast,engines,fly,airport',
      'Trailer|tow,behind,haul,hitch,truck',
      'Kayak|paddle,narrow,water,seat,river',
      'Roller coaster|track,drop,ride,loop,park',
      'Segway|two wheels,stand,balance,ride,handle',
      'Freight train|cars,cargo,track,long,engine',
      'Snowplow|snow,street,push,blade,clear',
      'Ice breaker|ship,arctic,crush,ice,path',
      'Rickshaw|pull,cart,seat,asia,ride',
      'Tugboat|push,harbor,small,strong,ship',
      'Zeppelin|blimp,airship,float,gas,sky',
      'Moped|small,engine,scooter,pedals,ride',
      'Dump truck|bed,tilt,dirt,haul,construction',
      'Sled|snow,hill,slide,runners,winter',
      'Barge|flat,river,cargo,push,slow',
      'Monorail|one rail,track,elevated,train,ride',
      'Streetcar|rails,city,electric,trolley,stop',
      'Hovercraft|air,cushion,skirt,glide,water',
      'Bulldozer|blade,push,tracks,dirt,heavy',
      'Cement mixer|drum,spin,truck,concrete,pour',
      'Tow truck|hook,pull,car,haul,winch',
      'Airboat|fan,swamp,flat,loud,glide',
      'Pedal boat|feet,lake,paddle,pedals,slow',
      'Cargo plane|freight,big,hold,load,fly',
      'Hydrofoil|lift,water,fast,wings,boat',
      'Handcar|pump,rails,lever,two,push'
    ],

    'Music': [
      'Drum|beat,sticks,hit,rhythm,snare',
      'Guitar|strings,strum,pick,chords,electric',
      'Piano|keys,black,white,bench,play',
      'Trumpet|brass,blow,valves,horn,loud',
      'Violin|bow,strings,chin,fiddle,orchestra',
      'Choir|sing,group,voices,robes,harmony',
      'Headphones|ears,listen,cord,music,over',
      'Microphone|sing,stand,amplify,voice,speak',
      'Orchestra|conductor,strings,concert,section,symphony',
      'Lyrics|words,song,sing,verse,write',
      'Tambourine|shake,jingle,hand,disc,rhythm',
      'Marching band|field,uniform,parade,step,instruments',
      'Harmonica|blow,mouth,pocket,harp,suck',
      'Xylophone|bars,mallets,notes,wood,strike',
      'Flute|blow,silver,holes,side,woodwind',
      'Concert|stage,tickets,crowd,live,perform',
      'Metronome|tick,tempo,beat,click,keep time',
      'Accordion|squeeze,bellows,buttons,fold,polka',
      'Banjo|strings,twang,country,round,pluck',
      'Cello|big,bow,sit,strings,low',
      'Saxophone|jazz,brass,reed,curve,blow',
      'Ukulele|small,four strings,hawaii,strum,guitar',
      'Melody|tune,notes,hum,catchy,line',
      'Chorus|repeat,song,part,sing,catchy',
      'Album|songs,record,cover,collection,release',
      'Speaker|sound,loud,box,play,volume',
      'Conductor|baton,wave,orchestra,lead,podium',
      'Bagpipes|scotland,drone,blow,bag,kilt',
      'Keyboard|electric,keys,plug,play,piano',
      'Rhythm|beat,timing,tap,steady,pulse',
      'Encore|again,end,crowd,cheer,extra',
      'Sheet music|notes,paper,read,stand,staff',
      'Duet|two,sing,together,pair,partner',
      'Bass|low,deep,strings,amp,rumble',
      'Recorder|plastic,school,holes,blow,squeak',
      'Gong|hit,metal,ring,big,mallet',
      'Solo|alone,one,spotlight,feature,part',
      'Cymbals|crash,brass,pair,clang,hit',
      'Amplifier|loud,plug,guitar,volume,amp',
      'Turntable|record,spin,needle,dj,vinyl',
      'Triangle|metal,ting,strike,three,small',
      'Maraca|shake,beads,pair,rattle,handle',
      'French horn|coiled,brass,hand,bell,round',
      'Trombone|slide,brass,push,pull,low',
      'Clarinet|reed,black,keys,woodwind,blow',
      'Oboe|reed,double,woodwind,tune,nasal',
      'Harp|strings,pluck,tall,frame,angel',
      'Organ|pipes,church,keys,pedals,loud',
      'Bongos|pair,hands,drums,small,tap',
      'Kazoo|hum,buzz,small,tube,silly'
    ],

    'Space': [
      'Telescope|look,stars,lens,night,observatory',
      'Comet|tail,ice,orbit,streak,halley',
      'Asteroid|rock,belt,space,orbit,crash',
      'Galaxy|milky way,stars,spiral,billions,huge',
      'Satellite|orbit,signal,dish,space,circle',
      'Crater|hole,moon,impact,round,dent',
      'Eclipse|block,sun,moon,shadow,dark',
      'Gravity|pull,fall,newton,weight,down',
      'Meteor|shower,streak,burn,shooting star,sky',
      'Orbit|circle,around,path,planet,loop',
      'Space station|orbit,astronauts,module,live,iss',
      'Constellation|stars,pattern,shape,night,dipper',
      'Black hole|pull,light,collapse,dark,gravity',
      'Rover|mars,wheels,explore,robot,drive',
      'Solar system|planets,sun,eight,orbit,ours',
      'Launch pad|rocket,countdown,liftoff,site,tower',
      'Spacesuit|helmet,oxygen,white,astronaut,pressure',
      'Moon landing|apollo,1969,footprint,flag,armstrong',
      'Nebula|cloud,gas,colorful,stars,birth',
      'Astronaut|space,suit,rocket,float,nasa',
      'Saturn|rings,planet,gas,sixth,giant',
      'Mars|red,planet,rover,fourth,dust',
      'Jupiter|biggest,spot,gas,planet,fifth',
      'Sunspot|dark,sun,cool,patch,cycle',
      'Light-year|distance,far,travel,measure,space',
      'Milky Way|galaxy,band,ours,stars,spiral',
      'Space shuttle|launch,orbiter,reusable,nasa,glide',
      'Zero gravity|float,weightless,space,drift,no pull',
      'Big Dipper|stars,ladle,seven,night,shape',
      'Aurora|lights,northern,green,sky,polar',
      'Probe|send,unmanned,explore,data,voyager',
      'Supernova|explode,star,bright,collapse,blast',
      'Astronomy|study,stars,science,night,charts',
      'Countdown|ten,launch,seconds,zero,rocket',
      'Lunar|moon,relating,cycle,eclipse,month',
      'Mission control|houston,screens,ground,team,radio',
      'Space debris|junk,orbit,pieces,trash,danger',
      'Pluto|dwarf,planet,cold,far,demoted',
      'Sun|star,hot,center,yellow,light',
      'Universe|everything,vast,expand,space,all',
      'Venus|hot,cloudy,second,planet,bright',
      'Mercury|closest,small,fast,planet,hot',
      'Neptune|blue,far,windy,planet,eighth',
      'Uranus|tilted,ice,seventh,planet,blue green',
      'Asteroid belt|between,mars,jupiter,rocks,ring',
      'Solar flare|burst,sun,radiation,eruption,storm',
      'Space elevator|cable,idea,up,tether,theory',
      'Escape velocity|speed,leave,gravity,needed,fast',
      'Docking|connect,station,latch,approach,join',
      'Reentry|return,heat,shield,atmosphere,burn'
    ],

    'Ocean': [
      'Coral reef|colorful,fish,ocean,barrier,polyps',
      'Seaweed|green,ocean,float,kelp,slimy',
      'Jellyfish|sting,clear,float,tentacles,blob',
      'Starfish|five,arms,tide pool,cling,sea star',
      'Lighthouse|beam,rocks,warn,tower,ships',
      'Tide|high,low,moon,in,out',
      'Seagull|bird,beach,squawk,fries,white',
      'Anchor|drop,boat,heavy,chain,hold',
      'Harbor|boats,dock,shelter,port,water',
      'Shipwreck|sunken,treasure,dive,broken,bottom',
      'Sea turtle|shell,swim,slow,beach,eggs',
      'Pearl|oyster,round,white,shiny,jewelry',
      'Scuba diving|tank,mask,underwater,fins,breathe',
      'Tidal pool|rocks,small,creatures,shallow,left',
      'Seahorse|tiny,curl,tail,swim,upright',
      'Barnacle|stick,hull,shell,cling,rock',
      'Wave|crash,surf,break,water,swell',
      'Sand dollar|flat,white,round,beach,shell',
      'Clam|shell,dig,two,chowder,sand',
      'Plankton|tiny,drift,food,microscopic,whale',
      'Kelp forest|tall,underwater,seaweed,sway,brown',
      'Manatee|slow,gentle,sea cow,florida,round',
      'Stingray|flat,tail,glide,sting,sand',
      'Lobster|claws,red,trap,boil,maine',
      'Buoy|float,marker,bell,water,bob',
      'Current|flow,move,water,gulf,drift',
      'Sea urchin|spines,round,spiky,rock,purple',
      'Trawler|net,fishing,boat,drag,catch',
      'Estuary|river,meet,ocean,brackish,mouth',
      'Marina|boats,slips,dock,park,harbor',
      'Sailor|ship,sea,navy,crew,rope',
      'Snorkel|tube,mask,breathe,surface,swim',
      'Dune|sand,hill,beach,grass,wind',
      'Coastline|edge,shore,map,water,land',
      'Undertow|pull,current,under,dangerous,drag',
      'Whirlpool|spin,water,swirl,funnel,drain',
      'Deep sea|dark,bottom,pressure,cold,trench',
      'Beachcomber|search,shells,walk,sand,find',
      'Foghorn|sound,warn,ships,low,blast',
      'Sea salt|water,evaporate,crystals,taste,ocean',
      'Tsunami|wave,huge,earthquake,coast,surge',
      'Coral bleaching|white,warm,dying,reef,stress',
      'Sonar|ping,depth,sound,detect,echo',
      'Ballast|weight,ship,steady,bottom,balance',
      'Trench|deep,narrow,ocean,bottom,mariana',
      'Sea breeze|cool,shore,afternoon,wind,off water',
      'Krill|tiny,shrimp,whale,food,swarm',
      'Bioluminescence|glow,dark,creatures,light,blue',
      'Reef shark|patrol,coral,fin,hunt,shallow',
      'Salt marsh|grass,tidal,shallow,birds,coastal'
    ],

    'Plants and Trees': [
      'Sunflower|tall,yellow,seeds,face,sun',
      'Cactus|spines,desert,water,prickly,green',
      'Acorn|oak,squirrel,nut,cap,fall',
      'Fern|frond,shade,green,curl,damp',
      'Vine|climb,grow,twist,ivy,wrap',
      'Pinecone|pine,scales,seeds,brown,fall',
      'Rose|thorns,red,petals,smell,love',
      'Bamboo|fast,hollow,panda,stalk,green',
      'Maple|leaf,syrup,tree,red,canada',
      'Dandelion|blow,yellow,weed,seeds,wish',
      'Moss|damp,green,soft,rock,shade',
      'Sapling|young,tree,thin,new,grow',
      'Orchard|trees,fruit,rows,apple,farm',
      'Willow|weeping,droop,branches,water,tree',
      'Tulip|bulb,spring,holland,cup,colorful',
      'Redwood|tall,giant,california,trunk,huge',
      'Seedling|sprout,young,small,soil,start',
      'Photosynthesis|sunlight,leaves,food,green,plant',
      'Greenhouse|glass,warm,plants,grow,indoor',
      'Compost|rot,scraps,soil,pile,rich',
      'Thorn|sharp,stem,prick,rose,point',
      'Nectar|sweet,flower,bee,drink,liquid',
      'Pollen|dust,yellow,bee,allergy,spread',
      'Bark|tree,outside,rough,trunk,peel',
      'Root|underground,anchor,water,grow,below',
      'Ivy|climb,wall,green,vine,cling',
      'Hedge|trim,bushes,row,fence,green',
      'Mushroom|fungus,cap,damp,spore,forest',
      'Cattail|pond,brown,tall,reed,marsh',
      'Clover|three,leaves,lucky,green,lawn',
      'Palm tree|tropical,coconut,fronds,beach,tall',
      'Evergreen|needles,winter,pine,green,stays',
      'Herb|cooking,basil,leaf,garden,flavor',
      'Bud|open,flower,new,tip,spring',
      'Trunk|tree,thick,wood,stand,middle',
      'Wildflower|meadow,grow,field,colorful,wild',
      'Sprout|grow,tiny,seed,push,new',
      'Prune|cut,trim,shears,branch,shape',
      'Cotton|soft,white,plant,boll,fabric',
      'Sequoia|giant,tree,huge,ancient,california',
      'Birch|white,bark,peel,thin,tree',
      'Aloe|gel,burn,spiky,plant,soothe',
      'Lily pad|float,pond,flat,green,frog',
      'Sap|sticky,tree,maple,flow,syrup',
      'Grafting|join,branch,tree,splice,grow',
      'Hydroponics|water,no soil,grow,nutrients,indoor',
      'Pollination|bee,flower,transfer,seed,spread',
      'Deciduous|drop,leaves,fall,bare,trees',
      'Canopy|top,branches,shade,forest,cover',
      'Understory|below,shade,plants,forest,layer'
    ],

    'Feelings': [
      'Excited|thrilled,jump,can\'t wait,happy,energy',
      'Nervous|jitters,worried,shaky,before,anxious',
      'Grateful|thankful,appreciate,thanks,glad,blessed',
      'Jealous|envy,want,someone else,green,covet',
      'Lonely|alone,no one,isolated,miss,by yourself',
      'Curious|wonder,question,explore,why,interested',
      'Frustrated|stuck,annoyed,try,give up,irritated',
      'Confident|sure,believe,stand tall,ready,certain',
      'Embarrassed|blush,red,cringe,mistake,ashamed',
      'Relieved|finally,over,exhale,better,worry gone',
      'Homesick|miss,home,away,family,sad',
      'Proud|accomplished,chest,earned,pleased,achievement',
      'Bored|nothing,dull,sigh,yawn,uninterested',
      'Surprised|shock,gasp,sudden,unexpected,wow',
      'Guilty|wrong,fault,sorry,conscience,blame',
      'Hopeful|wish,better,future,optimistic,believe',
      'Overwhelmed|too much,drowning,stress,pile,cope',
      'Content|satisfied,enough,calm,peaceful,fine',
      'Impatient|hurry,wait,tap,now,restless',
      'Sympathetic|feel for,care,comfort,understand,kind',
      'Furious|angry,rage,steam,mad,boiling',
      'Amused|funny,laugh,smile,entertained,giggle',
      'Determined|won\'t quit,goal,push,focused,persist',
      'Cautious|careful,slow,risk,watch,wary',
      'Disappointed|let down,expected,sad,hoped,failed',
      'Astonished|amazed,jaw,stunned,shock,wow',
      'Peaceful|calm,quiet,still,relaxed,serene',
      'Anxious|worried,nervous,stomach,fret,uneasy',
      'Delighted|pleased,happy,thrilled,joy,smile',
      'Confused|lost,unclear,huh,puzzled,muddled',
      'Brave|courage,fear,face,bold,hero',
      'Shy|quiet,hide,timid,back,blush',
      'Stubborn|won\'t budge,mule,refuse,fixed,insist',
      'Eager|ready,keen,can\'t wait,willing,excited',
      'Ashamed|shame,hide,wrong,face,guilty',
      'Comforted|better,hug,soothed,calm,cared for',
      'Envious|want,jealous,theirs,wish,covet',
      'Restless|can\'t sit,fidget,move,pacing,antsy',
      'Sincere|honest,mean it,genuine,true,real',
      'Optimistic|positive,bright side,hope,glass half full,expect good',
      'Nostalgic|miss,past,memory,fond,remember',
      'Skeptical|doubt,unsure,question,proof,unconvinced',
      'Indifferent|don\'t care,neutral,shrug,neither,unmoved',
      'Elated|thrilled,high,joy,soaring,overjoyed',
      'Apprehensive|uneasy,ahead,dread,worried,hesitant',
      'Compassionate|kind,care,suffering,help,warm',
      'Resentful|bitter,grudge,unfair,hold,sour',
      'Wistful|longing,dreamy,sad,wish,far off',
      'Flustered|rattled,confused,hurried,mixed up,thrown',
      'Reassured|calm,told,better,eased,comforted'
    ],

    'Buildings and Places': [
      'Skyscraper|tall,city,floors,glass,building',
      'Castle|king,moat,stone,towers,medieval',
      'Barn|red,farm,hay,animals,loft',
      'Museum|exhibit,art,visit,guide,collection',
      'Hospital|doctors,beds,emergency,sick,nurses',
      'Stadium|seats,crowd,field,game,arena',
      'Bridge|cross,river,span,over,cables',
      'Tunnel|through,mountain,dark,dig,under',
      'Church|steeple,pews,bells,service,windows',
      'Airport|planes,gates,luggage,runway,terminal',
      'Windmill|blades,wind,dutch,turn,grind',
      'Igloo|ice,blocks,dome,arctic,shelter',
      'Treehouse|branches,ladder,kids,wood,up',
      'Aquarium|tanks,fish,glass,visit,water',
      'Bakery|bread,smell,cases,oven,shop',
      'Firehouse|truck,pole,firefighters,station,alarm',
      'Courthouse|judge,steps,columns,trial,law',
      'Greenhouse|glass,plants,warm,grow,humid',
      'Motel|rooms,parking,sign,stay,highway',
      'Silo|tall,grain,farm,round,storage',
      'Pier|dock,wood,water,walk,out',
      'Dam|water,hold,concrete,river,power',
      'Fort|walls,defend,soldiers,build,guard',
      'Cabin|logs,woods,small,fireplace,rustic',
      'Mall|stores,food court,shop,parking,indoor',
      'Post office|stamps,mail,counter,packages,line',
      'Pyramid|egypt,stone,triangle,pharaoh,ancient',
      'Lighthouse|beam,rocks,tower,warn,coast',
      'Farmhouse|porch,fields,white,rural,kitchen',
      'Gas station|pump,fuel,stop,car,convenience',
      'Warehouse|boxes,storage,forklift,big,shelves',
      'Amphitheater|seats,stage,curve,outdoor,rows',
      'Observatory|telescope,dome,stars,study,hill',
      'Ranch|cattle,land,horses,west,acres',
      'Bunker|underground,concrete,safe,shelter,thick',
      'Studio|record,film,work,artist,room',
      'Cottage|small,cozy,garden,country,charming',
      'Skatepark|ramps,bowl,concrete,tricks,rails',
      'Campground|tents,sites,fire ring,park,camp',
      'Boardwalk|planks,beach,shops,walk,ocean',
      'Train station|platform,tracks,tickets,arrive,depart',
      'Bank|money,vault,teller,deposit,account',
      'Zoo|animals,exhibits,cages,visit,keeper',
      'Theater|stage,seats,curtain,play,audience',
      'Apartment|units,floors,rent,building,neighbors',
      'Cathedral|huge,stained glass,arches,church,spires',
      'Marketplace|stalls,vendors,buy,crowd,open',
      'Reservoir|water,supply,lake,dam,stored',
      'Shed|backyard,tools,small,wood,storage',
      'Village|small,houses,rural,town,community'
    ],

    'Tools and Machines': [
      'Hammer|nail,pound,claw,handle,strike',
      'Screwdriver|screw,turn,phillips,flathead,twist',
      'Wrench|bolt,turn,adjustable,grip,tighten',
      'Drill|hole,bit,spin,power,bore',
      'Saw|cut,teeth,wood,blade,back and forth',
      'Pliers|grip,pinch,wire,squeeze,jaws',
      'Level|bubble,straight,even,line,check',
      'Tape measure|inches,pull,retract,length,metal',
      'Ladder|rungs,climb,lean,tall,steps',
      'Crowbar|pry,bend,lever,iron,force',
      'Chainsaw|teeth,gas,tree,loud,cut',
      'Sandpaper|rough,smooth,rub,grit,sand',
      'Clamp|hold,tighten,squeeze,grip,secure',
      'Bulldozer|push,dirt,blade,tracks,construction',
      'Crane|lift,hook,tall,build,boom',
      'Forklift|pallet,lift,warehouse,prongs,drive',
      'Jackhammer|break,concrete,loud,pound,street',
      'Wheelbarrow|one wheel,push,dirt,handles,haul',
      'Anvil|blacksmith,heavy,hammer,iron,shape',
      'Furnace|heat,burn,basement,warm,fire',
      'Generator|power,electricity,gas,backup,run',
      'Compressor|air,pressure,tank,hose,pump',
      'Lathe|spin,shape,wood,turn,tool',
      'Vise|clamp,bench,hold,jaws,tighten',
      'Chisel|carve,wood,blade,tap,shape',
      'Blowtorch|flame,heat,metal,fuel,melt',
      'Conveyor belt|move,factory,line,carry,loop',
      'Printing press|ink,paper,type,print,gutenberg',
      'Sewing machine|needle,thread,stitch,pedal,fabric',
      'Blender|blend,pitcher,smoothie,chop,motor',
      'Lawn mower|grass,cut,push,blade,yard',
      'Chain|links,metal,pull,strong,loop',
      'Pulley|rope,wheel,lift,easier,system',
      'Gear|teeth,turn,machine,mesh,cog',
      'Lever|pry,fulcrum,lift,bar,simple machine',
      'Nail gun|fire,nails,air,fast,build',
      'Socket wrench|ratchet,click,bolt,set,turn',
      'Trowel|flat,spread,cement,garden,scoop',
      'Axe|chop,wood,handle,blade,swing',
      'Magnet|attract,metal,poles,stick,north',
      'Battery|power,charge,double a,positive,dead',
      'Spring|coil,bounce,metal,compress,tension',
      'Piston|engine,up down,cylinder,push,motor',
      'Valve|open,close,flow,control,pipe',
      'Nozzle|spray,hose,tip,direct,narrow',
      'Winch|cable,pull,crank,wind,tow',
      'Scaffolding|frame,build,climb,platform,temporary',
      'Excavator|dig,bucket,arm,tracks,scoop',
      'Sander|smooth,vibrate,wood,finish,power',
      'Toolbox|carry,tools,latch,handle,tray'
    ],

    'Holidays and Celebrations': [
      'Birthday|cake,candles,presents,party,age',
      'Fireworks|explode,sky,colors,boom,fourth',
      'Parade|floats,march,street,band,crowd',
      'Costume|dress up,halloween,pretend,mask,outfit',
      'Wedding|bride,groom,rings,vows,aisle',
      'Graduation|cap,gown,diploma,walk,ceremony',
      'Thanksgiving|turkey,family,november,feast,thanks',
      'New Year|midnight,countdown,resolution,january,confetti',
      'Piñata|candy,swing,blindfold,break,hang',
      'Anniversary|years,couple,celebrate,date,mark',
      'Trick-or-treat|candy,doorbell,costume,bag,halloween',
      'Confetti|throw,paper,colorful,celebrate,shower',
      'Toast|glass,raise,speech,cheers,celebrate',
      'Banner|hang,letters,sign,congratulations,string',
      'Reunion|family,gather,years,see,meet',
      'Picnic|blanket,basket,park,outside,eat',
      'Bonfire|logs,flames,gather,night,outdoors',
      'Carnival|rides,games,tickets,cotton candy,fair',
      'Balloon|helium,pop,string,float,party',
      'Gift wrap|paper,tape,bow,cover,present',
      'Ribbon|tie,bow,curl,gift,strip',
      'Feast|big meal,table,many,eat,spread',
      'Ceremony|formal,event,speech,mark,occasion',
      'Sparkler|hold,glow,sparks,stick,night',
      'Marching band|parade,uniforms,instruments,step,field',
      'Countdown|ten,zero,seconds,shout,midnight',
      'Cake|layers,frosting,slice,candles,bake',
      'Invitation|card,rsvp,mail,invite,party',
      'Float|parade,decorated,ride,platform,tow',
      'Costume party|dress up,theme,guests,mask,fun',
      'Fair|rides,livestock,booths,county,prizes',
      'Potluck|dish,bring,share,table,everyone',
      'Fasting|no food,skip,religious,hungry,abstain',
      'Lantern|light,hang,paper,glow,carry',
      'Harvest festival|crops,fall,celebrate,thanks,gather',
      'Dance|move,music,floor,partner,steps',
      'Trophy|win,gold,shelf,award,cup',
      'Medal|neck,ribbon,gold,award,win',
      'Speech|podium,talk,audience,notes,address',
      'Applause|clap,hands,crowd,cheer,ovation',
      'Streamer|hang,paper,twist,decorate,colorful',
      'Centerpiece|table,middle,flowers,decorate,display',
      'Guest list|names,invite,who,count,rsvp',
      'Party favor|small,gift,take home,bag,guests',
      'Costume contest|judge,best,prize,dress up,winner',
      'Countdown clock|numbers,tick,zero,display,wait',
      'Cheer|shout,crowd,yell,support,hooray',
      'Souvenir|keep,trip,remember,buy,memento',
      'Candle|wax,wick,flame,blow,melt',
      'Photo booth|pictures,strip,curtain,props,pose'
    ],

    'Stories and Movies': [
      'Hero|save,brave,main,good,protagonist',
      'Villain|bad,evil,plot,enemy,defeat',
      'Plot|story,events,twist,happens,arc',
      'Sequel|second,follow,part two,continue,after',
      'Cliffhanger|end,suspense,wait,unresolved,hang',
      'Narrator|tells,voice,story,describes,speaks',
      'Chapter|book,section,number,part,read',
      'Screenplay|script,movie,write,dialogue,scenes',
      'Subtitle|words,bottom,read,translate,screen',
      'Soundtrack|music,movie,songs,score,album',
      'Cartoon|animated,drawn,funny,saturday,characters',
      'Documentary|real,facts,film,true,narrate',
      'Comedy|funny,laugh,jokes,humor,light',
      'Mystery|clue,solve,who,detective,secret',
      'Fairy tale|once upon,princess,magic,moral,ending',
      'Fable|animals,moral,lesson,short,aesop',
      'Myth|gods,ancient,legend,greek,story',
      'Sidekick|helper,partner,second,friend,along',
      'Trailer|preview,coming soon,clips,short,ad',
      'Sequence|order,scenes,follow,series,steps',
      'Costume designer|clothes,film,make,character,sew',
      'Director|calls,action,film,vision,chair',
      'Stunt|dangerous,double,action,fall,trick',
      'Special effects|computer,explosion,fake,cgi,magic',
      'Character|person,story,role,played,who',
      'Setting|where,when,place,scene,background',
      'Conflict|problem,fight,struggle,tension,against',
      'Resolution|end,solved,wrap up,fixed,conclusion',
      'Flashback|earlier,memory,before,past,scene',
      'Prequel|before,earlier,first,origin,came',
      'Superhero|powers,cape,save,mask,comic',
      'Fantasy|magic,dragons,make believe,wizard,imaginary',
      'Adventure|journey,quest,travel,excitement,brave',
      'Suspense|tense,waiting,edge,nervous,build',
      'Illustration|picture,drawing,book,art,page',
      'Poem|verse,rhyme,lines,stanza,read',
      'Novel|book,long,fiction,chapters,story',
      'Biography|life,real person,story,written,about',
      'Audience|watch,seats,crowd,viewers,listen',
      'Intermission|break,middle,pause,stretch,halfway',
      'Credits|names,end,roll,scroll,list',
      'Script|lines,read,actors,pages,write',
      'Rehearsal|practice,run through,before,lines,prepare',
      'Premiere|first,opening,night,debut,red carpet',
      'Sequel hook|hint,end,next,setup,tease',
      'Moral|lesson,point,teach,end,message',
      'Genre|type,kind,category,horror,style',
      'Protagonist|main,lead,hero,center,follows',
      'Dialogue|talk,lines,between,speech,conversation',
      'Epilogue|after,end,later,wrap,final'
    ],

    'Nature and Landforms': [
      'Canyon|deep,walls,grand,river,carved',
      'Volcano|erupt,lava,ash,cone,magma',
      'Glacier|ice,slow,move,carve,cold',
      'Waterfall|drop,cliff,rush,mist,falls',
      'Desert|dry,sand,cactus,hot,little rain',
      'Swamp|wet,murky,alligator,marsh,soggy',
      'Prairie|grass,flat,open,plains,wide',
      'Cliff|steep,edge,drop,rock,face',
      'Cave|dark,underground,bats,stalactite,hollow',
      'Valley|between,low,hills,river,dip',
      'Plateau|flat,high,top,mesa,raised',
      'Peninsula|land,water,three sides,jut,florida',
      'Island|surrounded,water,land,shore,alone',
      'Delta|river,mouth,fan,silt,spread',
      'Geyser|shoot,hot,water,steam,erupt',
      'Sand dune|wind,pile,desert,shift,slope',
      'Rainforest|wet,trees,canopy,amazon,dense',
      'Tundra|frozen,cold,treeless,arctic,flat',
      'Fjord|narrow,cliffs,water,norway,inlet',
      'Marsh|wet,reeds,shallow,birds,soggy',
      'Ridge|top,line,mountain,long,crest',
      'Summit|top,peak,climb,highest,reach',
      'Foothill|base,small,before,mountain,rolling',
      'Boulder|big,rock,round,heavy,loose',
      'Stream|small,water,flow,creek,brook',
      'Pond|small,still,water,frogs,shallow',
      'Lagoon|shallow,reef,calm,water,tropical',
      'Oasis|desert,water,palm,green,spot',
      'Sinkhole|collapse,ground,hole,sudden,cave in',
      'Erosion|wear,wash,away,soil,slow',
      'Sediment|settle,bottom,layers,silt,deposit',
      'Fossil|bone,rock,ancient,dig,imprint',
      'Mineral|rock,crystal,mine,quartz,earth',
      'Quarry|dig,stone,pit,cut,rock',
      'Meadow|grass,open,flowers,field,soft',
      'Grove|trees,small,cluster,shade,group',
      'Bay|water,curve,coast,inlet,harbor',
      'Strait|narrow,between,water,channel,connect',
      'Continent|large,land,seven,africa,mass',
      'Equator|middle,line,earth,hot,zero',
      'Hemisphere|half,earth,north,south,globe',
      'Latitude|lines,across,north,south,measure',
      'Longitude|lines,up down,east,west,measure',
      'Watershed|drain,area,rivers,collect,basin',
      'Ecosystem|living,connected,habitat,balance,system',
      'Habitat|home,live,animal,environment,place',
      'Wetland|soggy,birds,protect,water,marsh',
      'Timberline|trees,stop,mountain,above,line',
      'Bedrock|solid,under,rock,base,deep',
      'Landslide|slide,rocks,hill,fall,rush'
    ],

    'Insects and Bugs': [
      'Ladybug|red,spots,beetle,lucky,small',
      'Dragonfly|wings,pond,hover,long,darting',
      'Grasshopper|jump,green,legs,chirp,field',
      'Caterpillar|crawl,fuzzy,leaf,butterfly,segments',
      'Firefly|glow,night,blink,light,summer',
      'Cricket|chirp,night,jump,sound,black',
      'Mosquito|bite,itch,buzz,blood,swat',
      'Termite|wood,eat,colony,damage,mound',
      'Praying mantis|green,front legs,fold,still,hunt',
      'Beetle|hard,shell,wings,crawl,bug',
      'Wasp|sting,nest,yellow,angry,paper',
      'Moth|light,night,dull,flutter,wings',
      'Centipede|many legs,crawl,long,fast,segments',
      'Millipede|legs,curl,slow,segments,many',
      'Tick|attach,skin,blood,tiny,woods',
      'Flea|jump,pet,itch,tiny,bite',
      'Cockroach|scurry,kitchen,brown,fast,pest',
      'Aphid|tiny,plants,green,suck,pest',
      'Hornet|sting,big,nest,angry,wasp',
      'Silkworm|silk,cocoon,thread,leaves,spin',
      'Stick insect|twig,camouflage,thin,still,branch',
      'Cicada|loud,summer,years,shell,buzz',
      'Weevil|snout,grain,tiny,pest,beetle',
      'Larva|young,grub,stage,hatch,before',
      'Pupa|cocoon,change,stage,rest,transform',
      'Cocoon|silk,wrap,inside,change,hang',
      'Chrysalis|butterfly,hard,hang,change,shell',
      'Antenna|feelers,head,sense,two,bug',
      'Exoskeleton|hard,outside,shell,shed,armor',
      'Hive|bees,honeycomb,buzz,box,home',
      'Anthill|dirt,mound,tunnels,ants,small',
      'Web|spider,silk,sticky,trap,strands',
      'Swarm|many,group,fly,cloud,together',
      'Nectar|sweet,flower,drink,bee,liquid',
      'Pollinate|flower,bee,pollen,spread,help',
      'Metamorphosis|change,stages,transform,caterpillar,become',
      'Stinger|sharp,sting,tail,bee,poke',
      'Mandible|jaw,bite,chew,mouth,strong',
      'Nymph|young,stage,grow,molt,before',
      'Molt|shed,skin,grow,leave,outgrow',
      'Insect repellent|spray,bugs,keep away,camping,skin',
      'Bug net|mesh,cover,protect,tent,keep out',
      'Butterfly garden|flowers,attract,plant,visit,wings',
      'Beehive|boxes,keeper,honey,frames,bees',
      'Locust|swarm,crops,eat,plague,grasshopper',
      'Horsefly|bite,big,painful,fly,summer',
      'Gnat|tiny,cloud,annoying,swarm,small',
      'Water strider|walk,pond,surface,legs,skim',
      'Roly-poly|curl,ball,gray,under,rock',
      'Earthworm|dirt,wiggle,soil,rain,long'
    ],

    'Colors and Shapes': [
      'Triangle|three,sides,point,angle,shape',
      'Rectangle|four,sides,long,corners,box',
      'Hexagon|six,sides,honeycomb,shape,stop',
      'Sphere|ball,round,3d,globe,solid',
      'Cylinder|can,round,tube,tall,3d',
      'Pyramid|point,triangle,egypt,base,3d',
      'Cube|six,sides,square,dice,box',
      'Cone|point,ice cream,round,traffic,top',
      'Oval|egg,stretched,circle,round,track',
      'Diamond|four,points,shape,tilted,rhombus',
      'Crescent|moon,curve,sliver,shape,horn',
      'Spiral|curl,around,snail,twist,coil',
      'Turquoise|blue,green,stone,bright,color',
      'Maroon|dark,red,brown,deep,color',
      'Lavender|light,purple,flower,soft,color',
      'Crimson|deep,red,blood,rich,color',
      'Beige|tan,light,brown,plain,neutral',
      'Charcoal|dark,gray,black,color,coal',
      'Gold|shiny,yellow,metal,rich,color',
      'Silver|shiny,gray,metal,coin,color',
      'Neon|bright,glow,sign,electric,vivid',
      'Pastel|soft,light,pale,gentle,color',
      'Stripe|line,band,pattern,across,zebra',
      'Polka dot|spots,round,pattern,repeat,circles',
      'Checkered|squares,black,white,pattern,flag',
      'Plaid|crossed,lines,pattern,flannel,scottish',
      'Zigzag|back,forth,angles,pattern,jagged',
      'Symmetry|same,mirror,both sides,balanced,fold',
      'Angle|corner,degrees,between,measure,point',
      'Parallel|never meet,same,lines,side by side,even',
      'Perpendicular|right angle,cross,ninety,meet,upright',
      'Curve|bend,arc,not straight,round,line',
      'Arc|curve,part,circle,bend,rainbow',
      'Diagonal|slant,corner,across,angle,tilted',
      'Outline|edge,border,trace,shape,around',
      'Silhouette|shadow,black,shape,outline,profile',
      'Shade|darker,tone,version,color,mix',
      'Tint|lighter,white,color,pale,mix',
      'Contrast|difference,light,dark,stand out,opposite',
      'Rainbow|colors,arc,seven,rain,spectrum',
      'Prism|split,light,triangle,glass,colors',
      'Spectrum|range,colors,light,band,order',
      'Primary colors|red,blue,yellow,basic,three',
      'Complementary|opposite,wheel,pair,contrast,colors',
      'Grid|lines,squares,rows,cross,pattern',
      'Pentagon|five,sides,shape,building,angles',
      'Octagon|eight,sides,stop sign,shape,angles',
      'Trapezoid|four,sides,one pair,parallel,shape',
      'Concentric|inside,rings,same center,circles,layers',
      'Tessellation|tile,repeat,fit,pattern,no gaps'
    ],

    'Toys and Playthings': [
      'Yo-yo|string,up,down,spin,trick',
      'Kite|string,wind,fly,tail,sky',
      'Jigsaw puzzle|pieces,fit,picture,edge,corner',
      'Building blocks|stack,tower,plastic,snap,build',
      'Marble|glass,roll,shooter,round,small',
      'Slingshot|rubber,y,shoot,pull,aim',
      'Bubble wand|blow,soap,pop,float,dip',
      'Jack-in-the-box|crank,pop,surprise,music,lid',
      'Rocking horse|wood,rock,ride,handle,back forth',
      'Toy soldier|plastic,green,army,stand,tiny',
      'Water balloon|fill,throw,burst,summer,wet',
      'Bouncy ball|rubber,high,bounce,small,super',
      'Board game|pieces,dice,turns,box,players',
      'Card deck|fifty-two,shuffle,suits,deal,pack',
      'Stuffed animal|soft,hug,plush,bear,toy',
      'Action figure|poseable,plastic,hero,small,collect',
      'Doll house|rooms,tiny,furniture,open,miniature',
      'Train set|tracks,loop,engine,cars,layout',
      'Kaleidoscope|turn,colors,tube,look,pattern',
      'Spinning top|spin,twist,balance,wobble,fall',
      'Pogo stick|bounce,spring,hop,handle,jump',
      'Hula hoop|waist,spin,plastic,circle,swing',
      'Sidewalk chalk|draw,color,pavement,wash,stick',
      'Play dough|squish,mold,colors,soft,shape',
      'Finger paint|hands,messy,colors,paper,smear',
      'Bubble blower|soap,ring,float,pop,wand',
      'Wind-up toy|key,crank,move,mechanical,walk',
      'Remote control car|drive,battery,steer,fast,radio',
      'Model airplane|glue,kit,build,wings,small',
      'Rubber duck|bath,yellow,squeak,float,tub',
      'Paper airplane|fold,throw,glide,sheet,fly',
      'Frisbee|throw,catch,disc,park,spin',
      'Jump rope|skip,turn,handles,double,rope',
      'Sandbox|sand,dig,bucket,shovel,play',
      'Swing set|chains,seat,push,back forth,pump',
      'Slide|down,ladder,slick,playground,ride',
      'Seesaw|up,down,balance,two,teeter',
      'Bubble bath|foam,tub,soap,suds,soak',
      'Sticker book|peel,stick,pages,collect,decorate',
      'Coloring book|crayons,pages,inside lines,pictures,fill',
      'Etch-a-sketch|knobs,draw,shake,erase,lines',
      'Magic set|tricks,cards,wand,perform,illusion',
      'Science kit|experiments,test tubes,mix,learn,box',
      'Walkie-talkie|talk,radio,over,button,pair',
      'Piggy bank|coins,save,slot,break,money',
      'Balloon animal|twist,shape,dog,clown,squeak',
      'Cardboard box|fort,imagine,tape,play,empty',
      'Tea set|cups,pretend,pour,saucer,tiny',
      'Bean bag|toss,soft,fill,throw,target',
      'Snow globe|shake,water,flakes,scene,dome'
    ],

    'Kitchen and Cooking': [
      'Whisk|beat,eggs,wire,stir,mix',
      'Spatula|flip,flat,pancake,turn,scrape',
      'Colander|drain,holes,pasta,rinse,bowl',
      'Rolling pin|roll,dough,flat,wood,push',
      'Measuring cup|amount,pour,lines,cup,measure',
      'Cutting board|chop,knife,wood,slice,surface',
      'Oven mitt|hot,hand,protect,pull,glove',
      'Ladle|soup,scoop,deep,pour,serve',
      'Grater|shred,cheese,holes,rub,box',
      'Peeler|skin,potato,strip,blade,peel',
      'Tongs|grip,pinch,grab,flip,two',
      'Skillet|pan,fry,handle,cast iron,stove',
      'Saucepan|pot,handle,boil,small,sauce',
      'Baking sheet|flat,cookies,oven,tray,metal',
      'Casserole dish|bake,glass,deep,oven,serve',
      'Mixing bowl|stir,large,batter,round,combine',
      'Timer|minutes,ding,set,count,alarm',
      'Preheat|oven,before,warm,degrees,wait',
      'Simmer|low,bubble,gentle,cook,slow',
      'Boil|bubble,water,hot,rolling,cook',
      'Sauté|pan,quick,oil,toss,fry',
      'Marinate|soak,flavor,hours,sauce,sit',
      'Knead|dough,push,fold,bread,hands',
      'Garnish|top,decorate,parsley,finish,plate',
      'Recipe|steps,ingredients,card,follow,directions',
      'Ingredient|part,list,add,item,recipe',
      'Leftovers|save,fridge,tomorrow,container,rest',
      'Freezer burn|dry,ice,ruined,frozen,white',
      'Apron|tie,protect,cook,front,cloth',
      'Blender|spin,smoothie,pitcher,chop,motor',
      'Rolling boil|fast,bubbles,water,full,hot',
      'Sift|flour,shake,fine,screen,separate',
      'Baste|spoon,juices,turkey,coat,over',
      'Dice|cut,cubes,small,chop,even',
      'Mince|tiny,chop,garlic,fine,pieces',
      'Fold|gently,mix,batter,over,combine',
      'Grease|butter,pan,slip,coat,oil',
      'Chill|fridge,cold,rest,dough,cool',
      'Season|salt,pepper,taste,add,flavor',
      'Broil|top,heat,brown,oven,high',
      'Steam|water,basket,vapor,cook,soft',
      'Grill|outside,grate,char,flame,cook',
      'Roast|oven,brown,meat,slow,pan',
      'Whip|beat,fluffy,cream,air,fast',
      'Curdle|separate,lumpy,spoil,milk,ruin',
      'Batter|liquid,mix,pour,pancake,thick',
      'Dough|thick,knead,bread,roll,sticky',
      'Crust|outside,pie,hard,edge,bake',
      'Zest|peel,lemon,scrape,flavor,outer',
      'Pinch|small,amount,salt,fingers,little'
    ],

    'Money and Shopping': [
      'Receipt|paper,proof,purchase,keep,total',
      'Coupon|discount,clip,save,expire,code',
      'Cashier|register,scan,checkout,pay,counter',
      'Shopping cart|push,wheels,aisle,fill,basket',
      'Price tag|cost,sticker,number,label,how much',
      'Sale|discount,percent,off,cheaper,deal',
      'Refund|money back,return,receipt,give,reverse',
      'Allowance|weekly,chores,parents,money,earn',
      'Budget|plan,spend,limit,money,stick to',
      'Savings|put away,account,later,grow,keep',
      'Debt|owe,borrow,pay back,loan,due',
      'Interest|extra,percent,bank,earn,charge',
      'Loan|borrow,pay back,bank,money,term',
      'Change|coins,back,leftover,cash,give',
      'Credit card|swipe,plastic,bill,charge,number',
      'Vending machine|coins,snack,drop,buttons,glass',
      'Barcode|lines,scan,beep,label,black',
      'Warranty|guarantee,repair,cover,year,promise',
      'Layaway|hold,pay,over time,store,reserve',
      'Bargain|cheap,deal,good price,steal,find',
      'Haggle|negotiate,price,lower,argue,deal',
      'Invoice|bill,owe,list,charges,send',
      'Deposit|put in,bank,account,down,add',
      'Withdrawal|take out,bank,atm,cash,remove',
      'Checkout|register,line,pay,end,scan',
      'Aisle|row,shelves,walk,store,between',
      'Clearance|last,cheap,rack,marked down,end',
      'Currency|money,dollars,country,exchange,bills',
      'Exchange rate|convert,money,country,value,trade',
      'Wallet|money,cards,pocket,fold,carry',
      'Piggy bank|coins,save,slot,break,ceramic',
      'Cash register|drawer,ring,total,money,counter',
      'Gift card|amount,plastic,spend,store,load',
      'Subscription|monthly,pay,renew,service,cancel',
      'Tip|extra,server,percent,leave,gratuity',
      'Tax|added,percent,government,pay,total',
      'Rebate|money back,mail,form,after,refund',
      'Delivery|bring,doorstep,order,truck,arrive',
      'Wholesale|bulk,cheaper,quantity,supply,large',
      'Retail|store,customer,price,sell,shop',
      'Inventory|stock,count,shelves,supply,list',
      'Merchandise|goods,items,sell,store,products',
      'Cashless|card,tap,no coins,digital,pay',
      'ATM|machine,cash,card,pin,withdraw',
      'Checkbook|write,sign,account,pay,stubs',
      'Marketplace|stalls,buy,sell,vendors,trade',
      'Donation|give,charity,money,help,gift',
      'Auction|bid,highest,gavel,sell,paddle',
      'Coin|round,metal,quarter,flip,change',
      'Bill|paper,dollar,twenty,fold,cash'
    ],

    'Computers and Phones': [
      'Keyboard|type,keys,letters,space bar,qwerty',
      'Mouse|click,cursor,pad,scroll,move',
      'Password|secret,login,letters,strong,type',
      'Download|save,internet,file,get,computer',
      'Upload|send,internet,share,post,up',
      'Screenshot|capture,screen,picture,save,snap',
      'Battery|charge,percent,dead,plug,power',
      'Charger|cord,plug,power,cable,battery',
      'Headphones|ears,listen,cord,music,wireless',
      'Wi-Fi|wireless,internet,signal,connect,network',
      'App|program,phone,download,icon,tap',
      'Browser|internet,tabs,search,web,open',
      'Search engine|type,results,find,web,query',
      'Email|send,inbox,message,at sign,attach',
      'Attachment|file,email,clip,send,include',
      'Folder|files,organize,open,store,directory',
      'Backup|copy,save,restore,spare,protect',
      'Update|new version,install,fix,download,newer',
      'Virus|bad,infect,computer,scan,harm',
      'Firewall|block,protect,security,network,barrier',
      'Cursor|arrow,blink,point,move,screen',
      'Scroll|move,down,wheel,page,swipe',
      'Zoom|bigger,smaller,in,out,pinch',
      'Touchscreen|tap,swipe,finger,glass,phone',
      'Speaker|sound,loud,play,volume,out',
      'Microphone|talk,record,voice,in,mute',
      'Webcam|video,camera,call,face,top',
      'Printer|paper,ink,print,tray,page',
      'Scanner|copy,glass,image,document,digitize',
      'Hard drive|storage,files,spin,space,disk',
      'Memory|ram,storage,gigabytes,hold,space',
      'Processor|chip,speed,brain,compute,cpu',
      'Monitor|screen,display,watch,pixels,see',
      'Laptop|portable,fold,screen,keyboard,carry',
      'Tablet|flat,touch,screen,portable,no keyboard',
      'Smartwatch|wrist,steps,notifications,band,small',
      'Bluetooth|wireless,pair,connect,short,devices',
      'Cloud|online,storage,internet,sync,remote',
      'Streaming|watch,online,live,buffer,play',
      'Notification|alert,pop,badge,ding,message',
      'Emoji|face,tiny,picture,text,smiley',
      'Group chat|many,message,thread,texts,everyone',
      'Voicemail|message,missed,recording,listen,call',
      'Ringtone|sound,call,phone,pick,tune',
      'Airplane mode|off,signal,flight,toggle,disconnect',
      'Data|usage,plan,megabytes,limit,cellular',
      'Charging cable|cord,plug,usb,connect,power',
      'Icon|small,picture,tap,app,symbol',
      'Home screen|icons,first,phone,unlock,main',
      'Software|program,install,code,run,application'
    ],

    'Farm and Garden': [
      'Tractor|drive,field,plow,wheels,farm',
      'Scarecrow|straw,hat,field,birds,pole',
      'Hay bale|round,stack,dry,grass,field',
      'Chicken coop|hens,eggs,wire,shelter,nest',
      'Plow|turn,soil,blade,field,break',
      'Harvest|gather,crops,fall,pick,collect',
      'Irrigation|water,pipes,crops,supply,spray',
      'Fertilizer|feed,soil,grow,spread,nutrients',
      'Weeds|unwanted,pull,grow,garden,pest',
      'Mulch|cover,soil,bark,spread,moisture',
      'Trellis|climb,support,vine,lattice,frame',
      'Wheelbarrow|push,one wheel,haul,handles,dirt',
      'Watering can|spout,pour,water,handle,plants',
      'Garden hose|water,coil,spray,long,nozzle',
      'Rake|leaves,teeth,gather,pull,yard',
      'Hoe|chop,weeds,soil,handle,blade',
      'Shovel|dig,scoop,handle,dirt,blade',
      'Seed packet|envelope,plant,picture,directions,small',
      'Sprout|new,green,push up,tiny,grow',
      'Transplant|move,replant,dig up,relocate,seedling',
      'Compost pile|rot,scraps,turn,rich,soil',
      'Pesticide|spray,bugs,kill,chemical,protect',
      'Greenhouse|glass,warm,grow,humid,plants',
      'Crop rotation|switch,fields,soil,years,plan',
      'Silo|tall,grain,round,store,farm',
      'Livestock|animals,cattle,farm,raise,herd',
      'Pasture|grass,graze,field,fence,animals',
      'Milking|cow,bucket,udder,twice,dairy',
      'Shearing|wool,sheep,clip,cut,spring',
      'Egg carton|dozen,cardboard,cups,eggs,close',
      'Barn owl|rafters,mice,night,white,hunt',
      'Furrow|row,groove,plow,line,dirt',
      'Orchard|fruit,trees,rows,pick,apple',
      'Vineyard|grapes,rows,vines,wine,hill',
      'Beehive|honey,frames,keeper,bees,box',
      'Sheepdog|herd,border collie,round up,farm,work',
      'Corral|fence,round,horses,pen,hold',
      'Trough|water,long,feed,animals,drink',
      'Bale twine|string,tie,hay,orange,wrap',
      'Combine|machine,harvest,grain,big,cut',
      'Sod|grass,roll,lay,lawn,turf',
      'Topsoil|top,rich,layer,dark,grow',
      'Drought|dry,no rain,crops,wilt,season',
      'Yield|amount,harvest,produce,bushels,output',
      'Grain bin|store,metal,corn,round,farm',
      'Pruning shears|cut,branch,snip,garden,blades',
      'Perennial|comes back,every year,plant,returns,lasting',
      'Annual|one season,replant,dies,yearly,plant',
      'Row cover|fabric,protect,frost,plants,drape',
      'Farmers market|stalls,fresh,saturday,local,produce'
    ],

    'History and Long Ago': [
      'Pharaoh|egypt,king,pyramid,ruler,ancient',
      'Knight|armor,sword,horse,castle,medieval',
      'Pioneer|wagon,west,settle,frontier,travel',
      'Explorer|discover,map,voyage,new,travel',
      'Colony|settle,new land,england,thirteen,settlement',
      'Revolution|change,overthrow,war,rebel,independence',
      'Constitution|document,rules,government,written,founding',
      'Telegraph|dots,dashes,wire,message,morse',
      'Steam engine|locomotive,power,coal,piston,invention',
      'Gold rush|west,miners,1849,claim,fortune',
      'Covered wagon|canvas,oxen,trail,west,family',
      'Trading post|frontier,goods,trade,store,remote',
      'Blacksmith|anvil,forge,horseshoe,hammer,iron',
      'Suffrage|vote,right,women,movement,win',
      'Abolition|end,slavery,movement,free,campaign',
      'Immigrant|arrive,new country,ellis island,move,settle',
      'Great Depression|1930s,jobs,poverty,soup line,crash',
      'World War|nations,global,soldiers,years,fight',
      'Civil rights|equal,march,protest,law,king',
      'Space race|moon,soviet,nasa,compete,1960s',
      'Scroll|roll,ancient,paper,unroll,writing',
      'Hieroglyph|egypt,picture,writing,carve,symbol',
      'Papyrus|egypt,paper,reed,write,ancient',
      'Aqueduct|rome,water,arches,carry,channel',
      'Coliseum|rome,arena,gladiator,ruins,round',
      'Gladiator|rome,arena,fight,sword,crowd',
      'Samurai|japan,sword,warrior,honor,armor',
      'Viking|ship,norse,raid,helmet,longboat',
      'Pilgrim|mayflower,plymouth,1620,settle,thanksgiving',
      'Mayflower|ship,pilgrims,voyage,1620,atlantic',
      'Cave painting|wall,ancient,ochre,animals,drawing',
      'Stone Age|early,tools,flint,prehistoric,stone',
      'Bronze Age|metal,tools,early,alloy,age',
      'Empire|rule,vast,emperor,conquer,lands',
      'Dynasty|family,rule,china,line,succession',
      'Silk Road|trade,route,asia,camels,goods',
      'Compass|needle,north,navigate,direction,round',
      'Printing press|type,books,gutenberg,ink,invention',
      'Renaissance|rebirth,art,europe,leonardo,new ideas',
      'Plague|disease,black,spread,death,medieval',
      'Castle moat|water,ditch,defend,around,drawbridge',
      'Drawbridge|lower,castle,chain,cross,gate',
      'Catapult|hurl,siege,launch,rock,arm',
      'Archaeologist|dig,artifacts,past,brush,site',
      'Artifact|object,old,dug up,museum,relic',
      'Ruins|remains,old,broken,site,ancient',
      'Time capsule|bury,future,box,open,later',
      'Treaty|agreement,signed,peace,nations,end war',
      'Frontier|edge,unsettled,west,border,wild',
      'Telegraph pole|wire,line,road,tall,carry'
    ],

    'Camping and Outdoors': [
      'Tent|poles,stakes,sleep,zipper,shelter',
      'Sleeping bag|zip,warm,roll,bag,night',
      'Campfire|logs,flames,ring,warm,sit',
      'Marshmallow|roast,stick,smore,white,sticky',
      'Lantern|light,hang,glow,camp,carry',
      'Flashlight|beam,batteries,dark,point,hand',
      'Compass|needle,north,direction,navigate,find',
      'Trail map|paths,folded,route,markers,paper',
      'Backpack|straps,carry,hike,frame,gear',
      'Hiking boots|ankle,laces,grip,trail,sturdy',
      'Canteen|water,carry,metal,strap,drink',
      'Camp stove|fuel,burner,cook,portable,small',
      'Cooler|ice,drinks,lid,keep cold,carry',
      'Bug spray|repellent,mosquito,skin,spray,keep away',
      'Sunscreen|lotion,burn,spf,rub,protect',
      'Trail mix|nuts,raisins,snack,bag,handful',
      'Firewood|logs,split,stack,burn,dry',
      'Kindling|small,sticks,start,fire,dry',
      'Matches|strike,box,light,flame,small',
      'Hatchet|chop,small,axe,wood,handle',
      'Rope|tie,coil,strong,knot,length',
      'Knot|tie,loop,rope,secure,bowline',
      'Hammock|hang,swing,two trees,nap,cloth',
      'Trailhead|start,sign,parking,path,begin',
      'Switchback|zigzag,steep,trail,turn,climb',
      'Summit|top,peak,reach,climb,highest',
      'Blaze|mark,tree,trail,paint,follow',
      'Campsite|spot,number,fire ring,tent,pitch',
      'Latrine|toilet,dig,camp,outdoor,pit',
      'Bear canister|food,seal,protect,cylinder,store',
      'Whistle|blow,loud,signal,emergency,three',
      'First aid kit|bandage,supplies,box,injury,help',
      'Poncho|rain,cover,head,plastic,drape',
      'Tarp|cover,ground,rain,plastic,stretch',
      'Stake|ground,push,tent,peg,secure',
      'Guy line|rope,tent,tighten,angle,steady',
      'Headlamp|forehead,band,hands free,light,beam',
      'Binoculars|look,far,two,lenses,birds',
      'Fishing pole|rod,reel,line,cast,catch',
      'Tackle box|hooks,lures,trays,fishing,latch',
      'Life jacket|orange,float,buckle,water,safety',
      'Paddle|canoe,stroke,blade,water,push',
      'Portage|carry,between,canoe,land,haul',
      'Wilderness|wild,remote,untouched,vast,nature',
      'Ranger station|park,info,help,cabin,rangers',
      'Leave no trace|pack out,clean,rule,respect,nothing',
      'Star gazing|night,sky,look,constellations,dark',
      'Dawn patrol|early,sunrise,start,before,hike',
      'Bug net|mesh,cover,head,protect,keep out',
      'Water filter|clean,pump,stream,drink,purify'
    ],

    'Art and Crafts': [
      'Paintbrush|bristles,handle,dip,stroke,paint',
      'Easel|stand,canvas,hold,three legs,tilt',
      'Canvas|cloth,stretch,paint,frame,surface',
      'Palette|colors,mix,thumb,board,paint',
      'Sketchbook|pages,draw,pencil,blank,carry',
      'Charcoal|black,smudge,draw,stick,dusty',
      'Watercolor|paint,water,wash,translucent,pan',
      'Acrylic|paint,fast,dry,thick,tube',
      'Clay|mold,wet,pottery,shape,fire',
      'Pottery wheel|spin,center,clay,foot,throw',
      'Kiln|fire,oven,harden,pottery,hot',
      'Glaze|shiny,coat,pottery,fire,finish',
      'Origami|fold,paper,crane,japan,shape',
      'Collage|glue,pieces,layer,magazine,cut',
      'Mosaic|tiles,pieces,pattern,glue,picture',
      'Stencil|cut out,trace,shape,spray,template',
      'Calligraphy|fancy,writing,pen,strokes,letters',
      'Woodcarving|knife,shape,wood,whittle,chips',
      'Knitting|needles,yarn,loops,stitch,scarf',
      'Crochet|hook,yarn,loop,stitch,chain',
      'Quilt|patches,sew,blanket,squares,layers',
      'Embroidery|thread,needle,stitch,design,hoop',
      'Weaving|loom,over,under,threads,cloth',
      'Loom|frame,weave,threads,warp,cloth',
      'Beadwork|string,beads,thread,pattern,tiny',
      'Pipe cleaner|fuzzy,bend,wire,twist,craft',
      'Glue stick|twist,paper,dry,white,stick',
      'Hot glue gun|melt,trigger,stick,burn,bond',
      'Scissors|cut,blades,handles,snip,pair',
      'Construction paper|colored,thick,cut,craft,sheets',
      'Tissue paper|thin,crumple,colored,layer,delicate',
      'Papier-mâché|paste,strips,mold,dry,layers',
      'Tie-dye|twist,rubber bands,colors,shirt,swirl',
      'Screen printing|squeegee,ink,mesh,shirt,press',
      'Linoleum block|carve,print,ink,press,stamp',
      'Sculpture|3d,carve,statue,form,shape',
      'Mural|wall,big,paint,public,scene',
      'Portrait|face,person,paint,likeness,pose',
      'Still life|objects,bowl,fruit,arranged,paint',
      'Landscape|scene,outdoors,paint,horizon,view',
      'Perspective|depth,vanishing point,far,near,3d',
      'Shading|dark,light,pencil,depth,blend',
      'Sketch|quick,rough,lines,draft,draw',
      'Gallery|hang,art,walls,show,visit',
      'Frame|border,hang,picture,edge,wood',
      'Varnish|coat,shiny,protect,seal,finish',
      'Smock|cover,paint,clothes,protect,apron',
      'Kiln shelf|stack,pottery,inside,post,hold',
      'Sculpting tool|shape,clay,carve,wire,pick',
      'Craft glitter|sparkle,mess,shake,tiny,shiny'
    ]
  };

  const CATEGORIES = Object.keys(DATA);

  /** 'Word|a,b,c' -> { word, related, category }. */
  function parse(line, category) {
    const cut = line.indexOf('|');
    return {
      word: line.slice(0, cut),
      related: line.slice(cut + 1).split(','),
      category: category
    };
  }

  const TERMS = {};
  for (const category of CATEGORIES) {
    TERMS[category] = DATA[category].map(line => parse(line, category));
  }

  function categories() {
    return CATEGORIES.slice();
  }

  function terms(category) {
    return TERMS[category] ? TERMS[category].slice() : [];
  }

  /**
   * Every term from the named categories, or from all of them, with each
   * word appearing once. A term can honestly belong to two categories —
   * a compass is a camping thing and a history thing — and `terms()` still
   * lists it under both. But a deck built from both must not hold it twice,
   * because a repeat inside one round is what makes a word game feel small.
   * First category named wins.
   */
  function pool(names) {
    // An omitted argument means every category; an empty array means an
    // empty pool. Collapsing the two would make "none picked" silently deal
    // the whole library, which is the opposite of what was asked for.
    const want = Array.isArray(names) ? names : CATEGORIES;
    const seen = new Set();
    const out = [];
    for (const name of want) {
      if (!TERMS[name]) continue;
      for (const term of TERMS[name]) {
        const key = term.word.toLowerCase();
        if (seen.has(key)) continue;
        seen.add(key);
        out.push(term);
      }
    }
    return out;
  }

  /**
   * A shuffled deck. Fisher-Yates on a copy, so a game can deal straight
   * through and only repeat once every term has been seen — a repeat inside
   * one round is the thing that makes a word game feel small.
   */
  function deck(names) {
    const cards = pool(names);
    for (let i = cards.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      const t = cards[i];
      cards[i] = cards[j];
      cards[j] = t;
    }
    return cards;
  }

  /** Names that are not in the library, for validating a saved setting. */
  function known(names) {
    if (!Array.isArray(names)) return [];
    return names.filter(n => CATEGORIES.indexOf(n) !== -1);
  }

  return { categories, terms, pool, deck, known };
})();
